app = 'ineptbot'
primary_region = 'lhr'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[processes]
app = "python main.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
